#include"stdio.h"
int main()
{
    int x;
    char ch;
    char string[20];
    long int c;
    double d;
    short int e;
    float f;
    printf("integer:");
    scanf("%d", &x);
    printf("\n%d", x);
    printf("\nCharacter:");
    fflush(stdin);
    scanf("%c", &ch);
    printf("\n%c", ch);
    printf("\n string:");
    scanf("%s", &string);
    printf("\n%s", string);
    printf("\nlong integer:");
    scanf("%ld", &c);
    printf("\n%ld", c);
    printf("\nShort integer:");
    scanf("%hd", &e);
    printf("\n%hd", e);
    printf("\nDouble:");
    scanf("%lf", &d);
    printf("\n%lf", d);
    printf("\nFloat:");
    scanf("%f", &f);
    printf("\n %f", f);
    printf("size of data types in C\n");
    printf("char=%d\n",sizeof(char));
    printf("signed char=%d\n",sizeof(signed char));
    printf("unsigned char%d\n",sizeof(unsigned char));
    printf("short=%d\n",sizeof(short));
    printf("short int=%d\n",sizeof(short int));
    printf("signed short=%d\n",sizeof(signed short));
    printf("signed short int=%d\n",sizeof(signed short int));
    printf("unsigned short=%d\n",sizeof(unsigned short));
    printf("unsigned short int=%d\n",sizeof(unsigned short int));
    printf("int=%d\n",sizeof(int));
    printf("signed=%d\n",sizeof(signed));
    printf("signed int=%d\n",sizeof(signed int));
    printf("insigned=%d\n",sizeof(unsigned));
    printf("unsigned int=%d\n",sizeof(unsigned int));
    printf("long=%d\n",sizeof(long));
    printf("long it=%d\n",sizeof(long int));
    printf("signed long=%d\n",sizeof(signed long));
    printf("signed long int=%d\n",sizeof(signed long int));
    printf("unsigned long=%d\n",sizeof(unsigned long));
    printf("unsigned long int=%d\n",sizeof(unsigned long int));
    printf("long long=%d\n",sizeof(long long));
    printf("long long int=%d\n",sizeof(long long int));
    printf("signed long long=%d\n",sizeof(signed long long));
    printf("signed long long int=%d\n",sizeof(signed long long int));
    printf("unsigned long long=%d\n",sizeof(unsigned long long));
    printf("unsigned long long int=%d\n",sizeof(unsigned long long int));
    printf("float=%d\n",sizeof(float));
    printf("double=%d\n",sizeof(double));
    printf("long double=%d\n",sizeof(long double));
    return 0;
}